version: '3.8'

services:
  api:
    build: .
    container_name: vortex-mp3-downloader-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    # Volumen para archivos temporales (opcional)
    volumes:
      - ./temp:/tmp/downloads
    restart: unless-stopped
